-- ============================================
-- 食谱分类数据迁移 - 从 CSV 导入完整分类体系
-- 在 Supabase Dashboard -> SQL Editor 中执行
-- ============================================

-- 0. 建表（如果不存在）
CREATE TABLE IF NOT EXISTS recipe_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  parent_id UUID REFERENCES recipe_categories(id) ON DELETE CASCADE,
  description TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 启用 RLS
ALTER TABLE recipe_categories ENABLE ROW LEVEL SECURITY;

-- RLS 策略：所有人可读
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'recipe_categories' AND policyname = 'Anyone can read categories'
  ) THEN
    CREATE POLICY "Anyone can read categories" ON recipe_categories
      FOR SELECT USING (true);
  END IF;
END $$;

-- 1. 清空旧分类数据（含示例数据）
DELETE FROM recipe_categories;

-- 2. 插入一级分类（CSV 文件名 = 一级分类名）
INSERT INTO recipe_categories (name, slug, parent_id, description, sort_order, is_active) VALUES
  ('蛋奶豆制品',   'cat-蛋奶豆制品',   NULL, '蛋、奶、豆制品类食材', 1, true),
  ('烘焙甜品饮料', 'cat-烘焙甜品饮料', NULL, '烘焙、甜品、饮品',     2, true),
  ('口味特色',     'cat-口味特色',     NULL, '按口味和烹饪方式分类', 3, true),
  ('米面干果腌咸', 'cat-米面干果腌咸', NULL, '米面、干果、腌制食品', 4, true),
  ('热门专题',     'cat-热门专题',     NULL, '热门菜谱专题合集',     5, true),
  ('肉类',         'cat-肉类',         NULL, '猪牛羊鸡鸭等肉类',     6, true),
  ('蔬菜水果',     'cat-蔬菜水果',     NULL, '蔬菜、水果、菌菇、花卉', 7, true),
  ('水产',         'cat-水产',         NULL, '鱼虾蟹贝等水产品',     8, true),
  ('汤粥主食',     'cat-汤粥主食',     NULL, '汤粥、米饭、面食',     9, true);

-- 3. 插入二级分类

-- === 蛋奶豆制品 (31) ===
INSERT INTO recipe_categories (name, slug, parent_id, sort_order, is_active)
SELECT name, slug, pid, sort_order, true FROM (
  SELECT '鸡蛋' AS name, 'cat-蛋奶豆制品-鸡蛋' AS slug, id AS pid, 1 AS sort_order FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '咸蛋', 'cat-蛋奶豆制品-咸蛋', id, 2 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '皮蛋', 'cat-蛋奶豆制品-皮蛋', id, 3 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '鹌鹑蛋', 'cat-蛋奶豆制品-鹌鹑蛋', id, 4 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '鸭蛋', 'cat-蛋奶豆制品-鸭蛋', id, 5 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '咸鸭蛋', 'cat-蛋奶豆制品-咸鸭蛋', id, 6 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '牛奶', 'cat-蛋奶豆制品-牛奶', id, 7 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '黄油', 'cat-蛋奶豆制品-黄油', id, 8 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '巧克力', 'cat-蛋奶豆制品-巧克力', id, 9 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '奶油', 'cat-蛋奶豆制品-奶油', id, 10 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '奶酪', 'cat-蛋奶豆制品-奶酪', id, 11 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '酸奶', 'cat-蛋奶豆制品-酸奶', id, 12 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '黑巧克力', 'cat-蛋奶豆制品-黑巧克力', id, 13 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '淡奶油', 'cat-蛋奶豆制品-淡奶油', id, 14 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '奶油奶酪', 'cat-蛋奶豆制品-奶油奶酪', id, 15 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '炼乳', 'cat-蛋奶豆制品-炼乳', id, 16 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '奶粉', 'cat-蛋奶豆制品-奶粉', id, 17 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '马苏里拉奶酪', 'cat-蛋奶豆制品-马苏里拉奶酪', id, 18 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '白巧克力', 'cat-蛋奶豆制品-白巧克力', id, 19 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '酸奶油', 'cat-蛋奶豆制品-酸奶油', id, 20 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '酥油', 'cat-蛋奶豆制品-酥油', id, 21 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '芝士', 'cat-蛋奶豆制品-芝士', id, 22 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '豆腐', 'cat-蛋奶豆制品-豆腐', id, 23 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '香干', 'cat-蛋奶豆制品-香干', id, 24 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '豆渣', 'cat-蛋奶豆制品-豆渣', id, 25 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '千张', 'cat-蛋奶豆制品-千张', id, 26 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '腐竹', 'cat-蛋奶豆制品-腐竹', id, 27 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '素鸡', 'cat-蛋奶豆制品-素鸡', id, 28 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '油豆皮', 'cat-蛋奶豆制品-油豆皮', id, 29 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '豆干', 'cat-蛋奶豆制品-豆干', id, 30 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
  UNION ALL SELECT '豆腐皮', 'cat-蛋奶豆制品-豆腐皮', id, 31 FROM recipe_categories WHERE slug = 'cat-蛋奶豆制品'
) AS t;

-- === 烘焙甜品饮料 (21) ===
INSERT INTO recipe_categories (name, slug, parent_id, sort_order, is_active)
SELECT name, slug, pid, sort_order, true FROM (
  SELECT '蛋糕' AS name, 'cat-烘焙甜品饮料-蛋糕' AS slug, id AS pid, 1 AS sort_order FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '面包', 'cat-烘焙甜品饮料-面包', id, 2 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '饼干', 'cat-烘焙甜品饮料-饼干', id, 3 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '披萨', 'cat-烘焙甜品饮料-披萨', id, 4 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '派', 'cat-烘焙甜品饮料-派', id, 5 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '司康', 'cat-烘焙甜品饮料-司康', id, 6 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '塔', 'cat-烘焙甜品饮料-塔', id, 7 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '泡芙', 'cat-烘焙甜品饮料-泡芙', id, 8 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '奶油霜', 'cat-烘焙甜品饮料-奶油霜', id, 9 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '布丁', 'cat-烘焙甜品饮料-布丁', id, 10 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '冷饮', 'cat-烘焙甜品饮料-冷饮', id, 11 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '果酱', 'cat-烘焙甜品饮料-果酱', id, 12 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '糖水', 'cat-烘焙甜品饮料-糖水', id, 13 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '冰淇淋', 'cat-烘焙甜品饮料-冰淇淋', id, 14 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '果冻', 'cat-烘焙甜品饮料-果冻', id, 15 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '咖啡', 'cat-烘焙甜品饮料-咖啡', id, 16 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '豆浆', 'cat-烘焙甜品饮料-豆浆', id, 17 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '奶茶', 'cat-烘焙甜品饮料-奶茶', id, 18 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '酒', 'cat-烘焙甜品饮料-酒', id, 19 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '果汁', 'cat-烘焙甜品饮料-果汁', id, 20 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
  UNION ALL SELECT '花草茶', 'cat-烘焙甜品饮料-花草茶', id, 21 FROM recipe_categories WHERE slug = 'cat-烘焙甜品饮料'
) AS t;

-- === 口味特色 (29) ===
INSERT INTO recipe_categories (name, slug, parent_id, sort_order, is_active)
SELECT name, slug, pid, sort_order, true FROM (
  SELECT '煎' AS name, 'cat-口味特色-煎' AS slug, id AS pid, 1 AS sort_order FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '蒸', 'cat-口味特色-蒸', id, 2 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '炖', 'cat-口味特色-炖', id, 3 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '红烧', 'cat-口味特色-红烧', id, 4 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '炸', 'cat-口味特色-炸', id, 5 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '卤', 'cat-口味特色-卤', id, 6 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '干锅', 'cat-口味特色-干锅', id, 7 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '火锅', 'cat-口味特色-火锅', id, 8 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '免烤', 'cat-口味特色-免烤', id, 9 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '辣', 'cat-口味特色-辣', id, 10 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '咖喱', 'cat-口味特色-咖喱', id, 11 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '糖醋', 'cat-口味特色-糖醋', id, 12 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '蒜香', 'cat-口味特色-蒜香', id, 13 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '酸甜', 'cat-口味特色-酸甜', id, 14 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '奶香', 'cat-口味特色-奶香', id, 15 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '孜然', 'cat-口味特色-孜然', id, 16 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '鱼香', 'cat-口味特色-鱼香', id, 17 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '五香', 'cat-口味特色-五香', id, 18 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '清淡', 'cat-口味特色-清淡', id, 19 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '烤箱', 'cat-口味特色-烤箱', id, 20 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '电饭煲', 'cat-口味特色-电饭煲', id, 21 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '微波炉', 'cat-口味特色-微波炉', id, 22 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '平底锅', 'cat-口味特色-平底锅', id, 23 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '塔吉锅', 'cat-口味特色-塔吉锅', id, 24 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '日式', 'cat-口味特色-日式', id, 25 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '韩式', 'cat-口味特色-韩式', id, 26 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '西式', 'cat-口味特色-西式', id, 27 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '西餐', 'cat-口味特色-西餐', id, 28 FROM recipe_categories WHERE slug = 'cat-口味特色'
  UNION ALL SELECT '东南亚', 'cat-口味特色-东南亚', id, 29 FROM recipe_categories WHERE slug = 'cat-口味特色'
) AS t;

-- === 热门专题 (38) ===
INSERT INTO recipe_categories (name, slug, parent_id, sort_order, is_active)
SELECT name, slug, pid, sort_order, true FROM (
  SELECT '家常菜' AS name, 'cat-热门专题-家常菜' AS slug, id AS pid, 1 AS sort_order FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '快手菜', 'cat-热门专题-快手菜', id, 2 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '下饭菜', 'cat-热门专题-下饭菜', id, 3 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '素菜', 'cat-热门专题-素菜', id, 4 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '大鱼大肉', 'cat-热门专题-大鱼大肉', id, 5 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '下酒菜', 'cat-热门专题-下酒菜', id, 6 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '小清新', 'cat-热门专题-小清新', id, 7 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '创意菜', 'cat-热门专题-创意菜', id, 8 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '小吃', 'cat-热门专题-小吃', id, 9 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '酱', 'cat-热门专题-酱', id, 10 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '沙拉', 'cat-热门专题-沙拉', id, 11 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '凉菜', 'cat-热门专题-凉菜', id, 12 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '零食', 'cat-热门专题-零食', id, 13 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '三明治', 'cat-热门专题-三明治', id, 14 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '月饼', 'cat-热门专题-月饼', id, 15 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '蒸蛋', 'cat-热门专题-蒸蛋', id, 16 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '寿司', 'cat-热门专题-寿司', id, 17 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '粽子', 'cat-热门专题-粽子', id, 18 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '鸡蛋羹', 'cat-热门专题-鸡蛋羹', id, 19 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '早餐', 'cat-热门专题-早餐', id, 20 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '下午茶', 'cat-热门专题-下午茶', id, 21 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '便当', 'cat-热门专题-便当', id, 22 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '圣诞节', 'cat-热门专题-圣诞节', id, 23 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '年夜饭', 'cat-热门专题-年夜饭', id, 24 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '深夜食堂', 'cat-热门专题-深夜食堂', id, 25 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '情人节', 'cat-热门专题-情人节', id, 26 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '宵夜', 'cat-热门专题-宵夜', id, 27 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '减肥', 'cat-热门专题-减肥', id, 28 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '美容', 'cat-热门专题-美容', id, 29 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '润肺抗燥', 'cat-热门专题-润肺抗燥', id, 30 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '补血', 'cat-热门专题-补血', id, 31 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '清热祛火', 'cat-热门专题-清热祛火', id, 32 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '儿童', 'cat-热门专题-儿童', id, 33 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '婴幼儿', 'cat-热门专题-婴幼儿', id, 34 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '老人', 'cat-热门专题-老人', id, 35 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '孕产妇', 'cat-热门专题-孕产妇', id, 36 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '宝宝食谱', 'cat-热门专题-宝宝食谱', id, 37 FROM recipe_categories WHERE slug = 'cat-热门专题'
  UNION ALL SELECT '味蕾工坊', 'cat-热门专题-味蕾工坊', id, 38 FROM recipe_categories WHERE slug = 'cat-热门专题'
) AS t;

-- === 汤粥主食 (11) ===
INSERT INTO recipe_categories (name, slug, parent_id, sort_order, is_active)
SELECT name, slug, pid, sort_order, true FROM (
  SELECT '炒饭' AS name, 'cat-汤粥主食-炒饭' AS slug, id AS pid, 1 AS sort_order FROM recipe_categories WHERE slug = 'cat-汤粥主食'
  UNION ALL SELECT '饭团', 'cat-汤粥主食-饭团', id, 2 FROM recipe_categories WHERE slug = 'cat-汤粥主食'
  UNION ALL SELECT '盖浇饭', 'cat-汤粥主食-盖浇饭', id, 3 FROM recipe_categories WHERE slug = 'cat-汤粥主食'
  UNION ALL SELECT '煲仔饭', 'cat-汤粥主食-煲仔饭', id, 4 FROM recipe_categories WHERE slug = 'cat-汤粥主食'
  UNION ALL SELECT '焗饭', 'cat-汤粥主食-焗饭', id, 5 FROM recipe_categories WHERE slug = 'cat-汤粥主食'
  UNION ALL SELECT '烩饭', 'cat-汤粥主食-烩饭', id, 6 FROM recipe_categories WHERE slug = 'cat-汤粥主食'
  UNION ALL SELECT '拌面', 'cat-汤粥主食-拌面', id, 7 FROM recipe_categories WHERE slug = 'cat-汤粥主食'
  UNION ALL SELECT '炒面', 'cat-汤粥主食-炒面', id, 8 FROM recipe_categories WHERE slug = 'cat-汤粥主食'
  UNION ALL SELECT '汤面', 'cat-汤粥主食-汤面', id, 9 FROM recipe_categories WHERE slug = 'cat-汤粥主食'
  UNION ALL SELECT '凉面', 'cat-汤粥主食-凉面', id, 10 FROM recipe_categories WHERE slug = 'cat-汤粥主食'
  UNION ALL SELECT '焖面', 'cat-汤粥主食-焖面', id, 11 FROM recipe_categories WHERE slug = 'cat-汤粥主食'
) AS t;

-- === 水产 (37) ===
INSERT INTO recipe_categories (name, slug, parent_id, sort_order, is_active)
SELECT name, slug, pid, sort_order, true FROM (
  SELECT '海水鱼' AS name, 'cat-水产-海水鱼' AS slug, id AS pid, 1 AS sort_order FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '淡水鱼', 'cat-水产-淡水鱼', id, 2 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '鱼头', 'cat-水产-鱼头', id, 3 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '鱼干', 'cat-水产-鱼干', id, 4 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '鱼籽', 'cat-水产-鱼籽', id, 5 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '鱼肚', 'cat-水产-鱼肚', id, 6 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '虾仁', 'cat-水产-虾仁', id, 7 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '海米', 'cat-水产-海米', id, 8 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '虾皮', 'cat-水产-虾皮', id, 9 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '明虾', 'cat-水产-明虾', id, 10 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '基围虾', 'cat-水产-基围虾', id, 11 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '龙虾', 'cat-水产-龙虾', id, 12 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '小龙虾', 'cat-水产-小龙虾', id, 13 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '河虾', 'cat-水产-河虾', id, 14 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '海虾', 'cat-水产-海虾', id, 15 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '皮皮虾', 'cat-水产-皮皮虾', id, 16 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '北极虾', 'cat-水产-北极虾', id, 17 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '虾干', 'cat-水产-虾干', id, 18 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '青虾', 'cat-水产-青虾', id, 19 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '草虾', 'cat-水产-草虾', id, 20 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '海白虾', 'cat-水产-海白虾', id, 21 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '虾米', 'cat-水产-虾米', id, 22 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '大虾', 'cat-水产-大虾', id, 23 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '蛤蜊', 'cat-水产-蛤蜊', id, 24 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '干贝', 'cat-水产-干贝', id, 25 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '鲍鱼', 'cat-水产-鲍鱼', id, 26 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '扇贝', 'cat-水产-扇贝', id, 27 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '牡蛎', 'cat-水产-牡蛎', id, 28 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '青口', 'cat-水产-青口', id, 29 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '蛏子', 'cat-水产-蛏子', id, 30 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '鲜贝', 'cat-水产-鲜贝', id, 31 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '北极贝', 'cat-水产-北极贝', id, 32 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '河蚌', 'cat-水产-河蚌', id, 33 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '梭子蟹', 'cat-水产-梭子蟹', id, 34 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '大闸蟹', 'cat-水产-大闸蟹', id, 35 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '蟹肉', 'cat-水产-蟹肉', id, 36 FROM recipe_categories WHERE slug = 'cat-水产'
  UNION ALL SELECT '蟹黄', 'cat-水产-蟹黄', id, 37 FROM recipe_categories WHERE slug = 'cat-水产'
) AS t;

-- === 肉类 (64) ===
INSERT INTO recipe_categories (name, slug, parent_id, sort_order, is_active)
SELECT name, slug, pid, sort_order, true FROM (
  SELECT '猪肉' AS name, 'cat-肉类-猪肉' AS slug, id AS pid, 1 AS sort_order FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '排骨', 'cat-肉类-排骨', id, 2 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪肉末', 'cat-肉类-猪肉末', id, 3 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '五花肉', 'cat-肉类-五花肉', id, 4 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪蹄', 'cat-肉类-猪蹄', id, 5 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '瘦肉', 'cat-肉类-瘦肉', id, 6 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '里脊', 'cat-肉类-里脊', id, 7 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪肝', 'cat-肉类-猪肝', id, 8 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪排', 'cat-肉类-猪排', id, 9 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪肚', 'cat-肉类-猪肚', id, 10 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪皮', 'cat-肉类-猪皮', id, 11 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪骨', 'cat-肉类-猪骨', id, 12 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '肥肠', 'cat-肉类-肥肠', id, 13 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪油', 'cat-肉类-猪油', id, 14 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪腰', 'cat-肉类-猪腰', id, 15 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪耳朵', 'cat-肉类-猪耳朵', id, 16 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪心', 'cat-肉类-猪心', id, 17 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪血', 'cat-肉类-猪血', id, 18 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '猪肺', 'cat-肉类-猪肺', id, 19 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '肉末', 'cat-肉类-肉末', id, 20 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸡翅', 'cat-肉类-鸡翅', id, 21 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸡胸', 'cat-肉类-鸡胸', id, 22 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸡腿', 'cat-肉类-鸡腿', id, 23 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸡爪', 'cat-肉类-鸡爪', id, 24 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸡肉', 'cat-肉类-鸡肉', id, 25 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '乌鸡', 'cat-肉类-乌鸡', id, 26 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸡胗', 'cat-肉类-鸡胗', id, 27 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '土鸡', 'cat-肉类-土鸡', id, 28 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '仔鸡', 'cat-肉类-仔鸡', id, 29 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '三黄鸡', 'cat-肉类-三黄鸡', id, 30 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸡肝', 'cat-肉类-鸡肝', id, 31 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '老母鸡', 'cat-肉类-老母鸡', id, 32 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸡心', 'cat-肉类-鸡心', id, 33 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '柴鸡', 'cat-肉类-柴鸡', id, 34 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '童子鸡', 'cat-肉类-童子鸡', id, 35 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '牛肉', 'cat-肉类-牛肉', id, 36 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '牛腩', 'cat-肉类-牛腩', id, 37 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '牛排', 'cat-肉类-牛排', id, 38 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '肥牛', 'cat-肉类-肥牛', id, 39 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '牛里脊', 'cat-肉类-牛里脊', id, 40 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '牛腱', 'cat-肉类-牛腱', id, 41 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '牛尾', 'cat-肉类-牛尾', id, 42 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '牛肉末', 'cat-肉类-牛肉末', id, 43 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '牛筋', 'cat-肉类-牛筋', id, 44 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '牛百叶', 'cat-肉类-牛百叶', id, 45 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '牛骨', 'cat-肉类-牛骨', id, 46 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '牛肉馅', 'cat-肉类-牛肉馅', id, 47 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '羊肉', 'cat-肉类-羊肉', id, 48 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '羊排', 'cat-肉类-羊排', id, 49 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '羊腿', 'cat-肉类-羊腿', id, 50 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '羊肉片', 'cat-肉类-羊肉片', id, 51 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '羊蝎子', 'cat-肉类-羊蝎子', id, 52 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸭腿', 'cat-肉类-鸭腿', id, 53 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸭肉', 'cat-肉类-鸭肉', id, 54 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '老鸭', 'cat-肉类-老鸭', id, 55 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸭胗', 'cat-肉类-鸭胗', id, 56 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸭血', 'cat-肉类-鸭血', id, 57 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸭掌', 'cat-肉类-鸭掌', id, 58 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸭翅', 'cat-肉类-鸭翅', id, 59 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸭舌', 'cat-肉类-鸭舌', id, 60 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸭肠', 'cat-肉类-鸭肠', id, 61 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸭脖', 'cat-肉类-鸭脖', id, 62 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸭肝', 'cat-肉类-鸭肝', id, 63 FROM recipe_categories WHERE slug = 'cat-肉类'
  UNION ALL SELECT '鸭爪', 'cat-肉类-鸭爪', id, 64 FROM recipe_categories WHERE slug = 'cat-肉类'
) AS t;

-- === 蔬菜水果 (162) ===
INSERT INTO recipe_categories (name, slug, parent_id, sort_order, is_active)
SELECT name, slug, pid, sort_order, true FROM (
  SELECT '彩椒' AS name, 'cat-蔬菜水果-彩椒' AS slug, id AS pid, 1 AS sort_order FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '番茄', 'cat-蔬菜水果-番茄', id, 2 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '南瓜', 'cat-蔬菜水果-南瓜', id, 3 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '玉米', 'cat-蔬菜水果-玉米', id, 4 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '茄子', 'cat-蔬菜水果-茄子', id, 5 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '黄瓜', 'cat-蔬菜水果-黄瓜', id, 6 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '豇豆', 'cat-蔬菜水果-豇豆', id, 7 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '青椒', 'cat-蔬菜水果-青椒', id, 8 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '苦瓜', 'cat-蔬菜水果-苦瓜', id, 9 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '冬瓜', 'cat-蔬菜水果-冬瓜', id, 10 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '丝瓜', 'cat-蔬菜水果-丝瓜', id, 11 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '秋葵', 'cat-蔬菜水果-秋葵', id, 12 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '西葫芦', 'cat-蔬菜水果-西葫芦', id, 13 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '毛豆', 'cat-蔬菜水果-毛豆', id, 14 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '豌豆', 'cat-蔬菜水果-豌豆', id, 15 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '四季豆', 'cat-蔬菜水果-四季豆', id, 16 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '荷兰豆', 'cat-蔬菜水果-荷兰豆', id, 17 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '蚕豆', 'cat-蔬菜水果-蚕豆', id, 18 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '圣女果', 'cat-蔬菜水果-圣女果', id, 19 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '扁豆', 'cat-蔬菜水果-扁豆', id, 20 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '刀豆', 'cat-蔬菜水果-刀豆', id, 21 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '瓠瓜', 'cat-蔬菜水果-瓠瓜', id, 22 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '玉米笋', 'cat-蔬菜水果-玉米笋', id, 23 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '西红柿', 'cat-蔬菜水果-西红柿', id, 24 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '时令水果', 'cat-蔬菜水果-时令水果', id, 25 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '柠檬', 'cat-蔬菜水果-柠檬', id, 26 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '椰子', 'cat-蔬菜水果-椰子', id, 27 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '草莓', 'cat-蔬菜水果-草莓', id, 28 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '橙', 'cat-蔬菜水果-橙', id, 29 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '牛油果', 'cat-蔬菜水果-牛油果', id, 30 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '木瓜', 'cat-蔬菜水果-木瓜', id, 31 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '山楂', 'cat-蔬菜水果-山楂', id, 32 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '蓝莓', 'cat-蔬菜水果-蓝莓', id, 33 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '西瓜', 'cat-蔬菜水果-西瓜', id, 34 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '柚子', 'cat-蔬菜水果-柚子', id, 35 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '火龙果', 'cat-蔬菜水果-火龙果', id, 36 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '樱桃', 'cat-蔬菜水果-樱桃', id, 37 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '西柚', 'cat-蔬菜水果-西柚', id, 38 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '桃', 'cat-蔬菜水果-桃', id, 39 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '葡萄', 'cat-蔬菜水果-葡萄', id, 40 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '金橘', 'cat-蔬菜水果-金橘', id, 41 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '黄桃', 'cat-蔬菜水果-黄桃', id, 42 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '百香果', 'cat-蔬菜水果-百香果', id, 43 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '杨梅', 'cat-蔬菜水果-杨梅', id, 44 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '桔子', 'cat-蔬菜水果-桔子', id, 45 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '荔枝', 'cat-蔬菜水果-荔枝', id, 46 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '无花果', 'cat-蔬菜水果-无花果', id, 47 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '石榴', 'cat-蔬菜水果-石榴', id, 48 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '杏子', 'cat-蔬菜水果-杏子', id, 49 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '桑葚', 'cat-蔬菜水果-桑葚', id, 50 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '哈密瓜', 'cat-蔬菜水果-哈密瓜', id, 51 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '柿子', 'cat-蔬菜水果-柿子', id, 52 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '李子', 'cat-蔬菜水果-李子', id, 53 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '青梅', 'cat-蔬菜水果-青梅', id, 54 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '枇杷', 'cat-蔬菜水果-枇杷', id, 55 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '香瓜', 'cat-蔬菜水果-香瓜', id, 56 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '甘蔗', 'cat-蔬菜水果-甘蔗', id, 57 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '覆盆子', 'cat-蔬菜水果-覆盆子', id, 58 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '杨桃', 'cat-蔬菜水果-杨桃', id, 59 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '橘子', 'cat-蔬菜水果-橘子', id, 60 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '金桔', 'cat-蔬菜水果-金桔', id, 61 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '杏', 'cat-蔬菜水果-杏', id, 62 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '土豆', 'cat-蔬菜水果-土豆', id, 63 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '萝卜', 'cat-蔬菜水果-萝卜', id, 64 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '紫薯', 'cat-蔬菜水果-紫薯', id, 65 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '红薯', 'cat-蔬菜水果-红薯', id, 66 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '胡萝卜', 'cat-蔬菜水果-胡萝卜', id, 67 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '山药', 'cat-蔬菜水果-山药', id, 68 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '藕', 'cat-蔬菜水果-藕', id, 69 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '芋头', 'cat-蔬菜水果-芋头', id, 70 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '笋', 'cat-蔬菜水果-笋', id, 71 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '茭白', 'cat-蔬菜水果-茭白', id, 72 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '马蹄', 'cat-蔬菜水果-马蹄', id, 73 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '牛蒡', 'cat-蔬菜水果-牛蒡', id, 74 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '菱角', 'cat-蔬菜水果-菱角', id, 75 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '芹菜', 'cat-蔬菜水果-芹菜', id, 76 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '白菜', 'cat-蔬菜水果-白菜', id, 77 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '韭菜', 'cat-蔬菜水果-韭菜', id, 78 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '菠菜', 'cat-蔬菜水果-菠菜', id, 79 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '西兰花', 'cat-蔬菜水果-西兰花', id, 80 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '圆白菜', 'cat-蔬菜水果-圆白菜', id, 81 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '花椰菜', 'cat-蔬菜水果-花椰菜', id, 82 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '莴苣', 'cat-蔬菜水果-莴苣', id, 83 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '青菜', 'cat-蔬菜水果-青菜', id, 84 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '娃娃菜', 'cat-蔬菜水果-娃娃菜', id, 85 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '生菜', 'cat-蔬菜水果-生菜', id, 86 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '甘蓝', 'cat-蔬菜水果-甘蓝', id, 87 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '蒜薹', 'cat-蔬菜水果-蒜薹', id, 88 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '紫甘蓝', 'cat-蔬菜水果-紫甘蓝', id, 89 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '空心菜', 'cat-蔬菜水果-空心菜', id, 90 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '油菜', 'cat-蔬菜水果-油菜', id, 91 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '荠菜', 'cat-蔬菜水果-荠菜', id, 92 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '香椿', 'cat-蔬菜水果-香椿', id, 93 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '茼蒿', 'cat-蔬菜水果-茼蒿', id, 94 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '菜心', 'cat-蔬菜水果-菜心', id, 95 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '芥兰', 'cat-蔬菜水果-芥兰', id, 96 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '黄花菜', 'cat-蔬菜水果-黄花菜', id, 97 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '韭黄', 'cat-蔬菜水果-韭黄', id, 98 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '苋菜', 'cat-蔬菜水果-苋菜', id, 99 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '紫苏', 'cat-蔬菜水果-紫苏', id, 100 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '芥菜', 'cat-蔬菜水果-芥菜', id, 101 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '油麦菜', 'cat-蔬菜水果-油麦菜', id, 102 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '豌豆苗', 'cat-蔬菜水果-豌豆苗', id, 103 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '苦菊', 'cat-蔬菜水果-苦菊', id, 104 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '青蒜', 'cat-蔬菜水果-青蒜', id, 105 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '鱼腥草', 'cat-蔬菜水果-鱼腥草', id, 106 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '马兰', 'cat-蔬菜水果-马兰', id, 107 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '蕨菜', 'cat-蔬菜水果-蕨菜', id, 108 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '西洋菜', 'cat-蔬菜水果-西洋菜', id, 109 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '水芹', 'cat-蔬菜水果-水芹', id, 110 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '儿菜', 'cat-蔬菜水果-儿菜', id, 111 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '豌豆尖', 'cat-蔬菜水果-豌豆尖', id, 112 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '芝麻菜', 'cat-蔬菜水果-芝麻菜', id, 113 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '芦蒿', 'cat-蔬菜水果-芦蒿', id, 114 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '穿心莲', 'cat-蔬菜水果-穿心莲', id, 115 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '孢子甘蓝', 'cat-蔬菜水果-孢子甘蓝', id, 116 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '萝卜苗', 'cat-蔬菜水果-萝卜苗', id, 117 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '红菜苔', 'cat-蔬菜水果-红菜苔', id, 118 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '牛至', 'cat-蔬菜水果-牛至', id, 119 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '蒿子杆', 'cat-蔬菜水果-蒿子杆', id, 120 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '包菜', 'cat-蔬菜水果-包菜', id, 121 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '莴笋', 'cat-蔬菜水果-莴笋', id, 122 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '花菜', 'cat-蔬菜水果-花菜', id, 123 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '蒜苔', 'cat-蔬菜水果-蒜苔', id, 124 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '豆苗', 'cat-蔬菜水果-豆苗', id, 125 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '披萨草', 'cat-蔬菜水果-披萨草', id, 126 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '香菇', 'cat-蔬菜水果-香菇', id, 127 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '杏鲍菇', 'cat-蔬菜水果-杏鲍菇', id, 128 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '银耳', 'cat-蔬菜水果-银耳', id, 129 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '木耳', 'cat-蔬菜水果-木耳', id, 130 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '金针菇', 'cat-蔬菜水果-金针菇', id, 131 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '蘑菇', 'cat-蔬菜水果-蘑菇', id, 132 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '茶树菇', 'cat-蔬菜水果-茶树菇', id, 133 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '平菇', 'cat-蔬菜水果-平菇', id, 134 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '松茸', 'cat-蔬菜水果-松茸', id, 135 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '鸡腿菇', 'cat-蔬菜水果-鸡腿菇', id, 136 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '草菇', 'cat-蔬菜水果-草菇', id, 137 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '竹荪', 'cat-蔬菜水果-竹荪', id, 138 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '蟹味菇', 'cat-蔬菜水果-蟹味菇', id, 139 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '花菇', 'cat-蔬菜水果-花菇', id, 140 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '猴头菇', 'cat-蔬菜水果-猴头菇', id, 141 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '牛肝菌', 'cat-蔬菜水果-牛肝菌', id, 142 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '灵芝', 'cat-蔬菜水果-灵芝', id, 143 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '榛蘑', 'cat-蔬菜水果-榛蘑', id, 144 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '白玉菇', 'cat-蔬菜水果-白玉菇', id, 145 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '姬松茸', 'cat-蔬菜水果-姬松茸', id, 146 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '滑子菇', 'cat-蔬菜水果-滑子菇', id, 147 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '发菜', 'cat-蔬菜水果-发菜', id, 148 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '白灵菇', 'cat-蔬菜水果-白灵菇', id, 149 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '袖珍菇', 'cat-蔬菜水果-袖珍菇', id, 150 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '双孢菇', 'cat-蔬菜水果-双孢菇', id, 151 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '秀珍菇', 'cat-蔬菜水果-秀珍菇', id, 152 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '茶叶', 'cat-蔬菜水果-茶叶', id, 153 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '桂花', 'cat-蔬菜水果-桂花', id, 154 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '玫瑰', 'cat-蔬菜水果-玫瑰', id, 155 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '薄荷', 'cat-蔬菜水果-薄荷', id, 156 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '菊花', 'cat-蔬菜水果-菊花', id, 157 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '洛神花', 'cat-蔬菜水果-洛神花', id, 158 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '茉莉花', 'cat-蔬菜水果-茉莉花', id, 159 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '槐花', 'cat-蔬菜水果-槐花', id, 160 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
  UNION ALL SELECT '金银花', 'cat-蔬菜水果-金银花', id, 161 FROM recipe_categories WHERE slug = 'cat-蔬菜水果'
) AS t;

-- === 米面干果腌咸 (119) ===
INSERT INTO recipe_categories (name, slug, parent_id, sort_order, is_active)
SELECT name, slug, pid, sort_order, true FROM (
  SELECT '面粉' AS name, 'cat-米面干果腌咸-面粉' AS slug, id AS pid, 1 AS sort_order FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '面条', 'cat-米面干果腌咸-面条', id, 2 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '大米', 'cat-米面干果腌咸-大米', id, 3 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '高筋面粉', 'cat-米面干果腌咸-高筋面粉', id, 4 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '意大利面', 'cat-米面干果腌咸-意大利面', id, 5 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '糯米', 'cat-米面干果腌咸-糯米', id, 6 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '低筋面粉', 'cat-米面干果腌咸-低筋面粉', id, 7 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '年糕', 'cat-米面干果腌咸-年糕', id, 8 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '西米', 'cat-米面干果腌咸-西米', id, 9 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '糯米粉', 'cat-米面干果腌咸-糯米粉', id, 10 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '粉丝', 'cat-米面干果腌咸-粉丝', id, 11 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '燕麦', 'cat-米面干果腌咸-燕麦', id, 12 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '米粉', 'cat-米面干果腌咸-米粉', id, 13 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '酒酿', 'cat-米面干果腌咸-酒酿', id, 14 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '燕麦片', 'cat-米面干果腌咸-燕麦片', id, 15 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '乌冬面', 'cat-米面干果腌咸-乌冬面', id, 16 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '小米', 'cat-米面干果腌咸-小米', id, 17 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '玉米面', 'cat-米面干果腌咸-玉米面', id, 18 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '全麦粉', 'cat-米面干果腌咸-全麦粉', id, 19 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '黑米', 'cat-米面干果腌咸-黑米', id, 20 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '魔芋', 'cat-米面干果腌咸-魔芋', id, 21 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '方便面', 'cat-米面干果腌咸-方便面', id, 22 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '粉条', 'cat-米面干果腌咸-粉条', id, 23 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '米线', 'cat-米面干果腌咸-米线', id, 24 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '荞麦面', 'cat-米面干果腌咸-荞麦面', id, 25 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '油条', 'cat-米面干果腌咸-油条', id, 26 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '黄豆面', 'cat-米面干果腌咸-黄豆面', id, 27 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '消化饼干', 'cat-米面干果腌咸-消化饼干', id, 28 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '面筋', 'cat-米面干果腌咸-面筋', id, 29 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '粘米粉', 'cat-米面干果腌咸-粘米粉', id, 30 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '凉粉', 'cat-米面干果腌咸-凉粉', id, 31 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '糙米', 'cat-米面干果腌咸-糙米', id, 32 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '河粉', 'cat-米面干果腌咸-河粉', id, 33 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '紫米', 'cat-米面干果腌咸-紫米', id, 34 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '烤麸', 'cat-米面干果腌咸-烤麸', id, 35 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '小麦胚芽', 'cat-米面干果腌咸-小麦胚芽', id, 36 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '澄面', 'cat-米面干果腌咸-澄面', id, 37 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '粉皮', 'cat-米面干果腌咸-粉皮', id, 38 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '蕨根粉', 'cat-米面干果腌咸-蕨根粉', id, 39 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '藕粉', 'cat-米面干果腌咸-藕粉', id, 40 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '红曲米', 'cat-米面干果腌咸-红曲米', id, 41 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '莜面', 'cat-米面干果腌咸-莜面', id, 42 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '黄米', 'cat-米面干果腌咸-黄米', id, 43 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '荞麦', 'cat-米面干果腌咸-荞麦', id, 44 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '大麦', 'cat-米面干果腌咸-大麦', id, 45 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '高粱米', 'cat-米面干果腌咸-高粱米', id, 46 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '红米', 'cat-米面干果腌咸-红米', id, 47 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '澄粉', 'cat-米面干果腌咸-澄粉', id, 48 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '黄豆粉', 'cat-米面干果腌咸-黄豆粉', id, 49 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '芝麻', 'cat-米面干果腌咸-芝麻', id, 50 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '花生', 'cat-米面干果腌咸-花生', id, 51 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '杏仁', 'cat-米面干果腌咸-杏仁', id, 52 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '红豆', 'cat-米面干果腌咸-红豆', id, 53 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '枣', 'cat-米面干果腌咸-枣', id, 54 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '核桃', 'cat-米面干果腌咸-核桃', id, 55 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '板栗', 'cat-米面干果腌咸-板栗', id, 56 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '蔓越莓', 'cat-米面干果腌咸-蔓越莓', id, 57 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '绿豆', 'cat-米面干果腌咸-绿豆', id, 58 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '黄豆', 'cat-米面干果腌咸-黄豆', id, 59 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '薏米', 'cat-米面干果腌咸-薏米', id, 60 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '葡萄干', 'cat-米面干果腌咸-葡萄干', id, 61 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '莲子', 'cat-米面干果腌咸-莲子', id, 62 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '橄榄', 'cat-米面干果腌咸-橄榄', id, 63 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '黑豆', 'cat-米面干果腌咸-黑豆', id, 64 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '蜜豆', 'cat-米面干果腌咸-蜜豆', id, 65 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '芸豆', 'cat-米面干果腌咸-芸豆', id, 66 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '腰果', 'cat-米面干果腌咸-腰果', id, 67 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '桃胶', 'cat-米面干果腌咸-桃胶', id, 68 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '乌梅', 'cat-米面干果腌咸-乌梅', id, 69 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '松仁', 'cat-米面干果腌咸-松仁', id, 70 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '无花果', 'cat-米面干果腌咸-无花果', id, 71 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '银杏果', 'cat-米面干果腌咸-银杏果', id, 72 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '话梅', 'cat-米面干果腌咸-话梅', id, 73 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '榛子', 'cat-米面干果腌咸-榛子', id, 74 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '鹰嘴豆', 'cat-米面干果腌咸-鹰嘴豆', id, 75 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '罗汉果', 'cat-米面干果腌咸-罗汉果', id, 76 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '芡实', 'cat-米面干果腌咸-芡实', id, 77 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '开心果', 'cat-米面干果腌咸-开心果', id, 78 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '干山楂', 'cat-米面干果腌咸-干山楂', id, 79 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '南瓜子', 'cat-米面干果腌咸-南瓜子', id, 80 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '瓜子仁', 'cat-米面干果腌咸-瓜子仁', id, 81 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '眉豆', 'cat-米面干果腌咸-眉豆', id, 82 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '红腰豆', 'cat-米面干果腌咸-红腰豆', id, 83 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '松子', 'cat-米面干果腌咸-松子', id, 84 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '山楂干', 'cat-米面干果腌咸-山楂干', id, 85 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '白果', 'cat-米面干果腌咸-白果', id, 86 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '火腿', 'cat-米面干果腌咸-火腿', id, 87 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '香肠', 'cat-米面干果腌咸-香肠', id, 88 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '培根', 'cat-米面干果腌咸-培根', id, 89 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '腊肉', 'cat-米面干果腌咸-腊肉', id, 90 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '酸菜', 'cat-米面干果腌咸-酸菜', id, 91 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '泡菜', 'cat-米面干果腌咸-泡菜', id, 92 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '肉松', 'cat-米面干果腌咸-肉松', id, 93 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '梅干菜', 'cat-米面干果腌咸-梅干菜', id, 94 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '雪里蕻', 'cat-米面干果腌咸-雪里蕻', id, 95 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '榨菜', 'cat-米面干果腌咸-榨菜', id, 96 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '辣白菜', 'cat-米面干果腌咸-辣白菜', id, 97 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '笋干', 'cat-米面干果腌咸-笋干', id, 98 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '鱼丸', 'cat-米面干果腌咸-鱼丸', id, 99 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '橄榄菜', 'cat-米面干果腌咸-橄榄菜', id, 100 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '咸菜', 'cat-米面干果腌咸-咸菜', id, 101 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '萝卜干', 'cat-米面干果腌咸-萝卜干', id, 102 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '咸肉', 'cat-米面干果腌咸-咸肉', id, 103 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '酸豇豆', 'cat-米面干果腌咸-酸豇豆', id, 104 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '肉丸', 'cat-米面干果腌咸-肉丸', id, 105 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '午餐肉', 'cat-米面干果腌咸-午餐肉', id, 106 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '蟹棒', 'cat-米面干果腌咸-蟹棒', id, 107 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '叉烧肉', 'cat-米面干果腌咸-叉烧肉', id, 108 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '芽菜', 'cat-米面干果腌咸-芽菜', id, 109 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '纳豆', 'cat-米面干果腌咸-纳豆', id, 110 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '大头菜', 'cat-米面干果腌咸-大头菜', id, 111 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '酸笋', 'cat-米面干果腌咸-酸笋', id, 112 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '木鱼花', 'cat-米面干果腌咸-木鱼花', id, 113 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '冬菜', 'cat-米面干果腌咸-冬菜', id, 114 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '玉兰片', 'cat-米面干果腌咸-玉兰片', id, 115 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '泡萝卜', 'cat-米面干果腌咸-泡萝卜', id, 116 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '咸黄瓜', 'cat-米面干果腌咸-咸黄瓜', id, 117 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '叉烧', 'cat-米面干果腌咸-叉烧', id, 118 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
  UNION ALL SELECT '酸豆角', 'cat-米面干果腌咸-酸豆角', id, 119 FROM recipe_categories WHERE slug = 'cat-米面干果腌咸'
) AS t;

-- 4. 给 custom_recipes 表添加分类ID字段（可选，用于关联查询）
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'custom_recipes' AND column_name = 'subcategory_id'
  ) THEN
    ALTER TABLE custom_recipes ADD COLUMN subcategory_id UUID REFERENCES recipe_categories(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 5. 验证
SELECT
  (SELECT COUNT(*) FROM recipe_categories WHERE parent_id IS NULL) AS level1_count,
  (SELECT COUNT(*) FROM recipe_categories WHERE parent_id IS NOT NULL) AS level2_count,
  (SELECT COUNT(*) FROM recipe_categories) AS total;

-- ============================================
-- 完成！共 9 个一级分类 + 512 个二级分类 = 521 条记录
-- ============================================
